### ISSUE TITLE
Calling getPumpStatus() is timing out. 

### ISSUE THREAD

**Issue by tjblevins** [parnic/node-screenlogic#45]
Hi Parnic, I have created a REST webservice using your Library and I love it!

Recently, I have been asked to expand to capture more Pump info and I noticed you added Pump Functions to the library. 

I created a copy of example.js and added the get getPumpStatus(). It seems to be timing out on that one function. 

Any ideas?

`  }).on('saltCellConfig', function(saltCellConfig) {
    this.getControllerConfig();
    console.log(' salt cell installed=' + saltCellConfig.installed);
//Adding Pump
}).on('pumpStatus', function(pumpStatus) {
    this.getPumpStatus(0);
    console.log(' Pump Status =' + pumpStatus.isRunning);
//Pump End
  }).on('controllerConfig', function(config) {
    console.log(' controller is in celsius=' + config.degC);
    client.close();`

**Comment by tjblevins** [comment]
Sorry you are correct I messed up when I adding the call to getPumpStatus(), thanks for pointing that out. I fixed that
![Screen Shot 2020-10-06 at 1 11 49 PM](https://user-images.githubusercontent.com/40493597/95243338-1adcb600-07d6-11eb-9ea6-fa4d29f33345.png)
![Screen Shot 2020-10-06 at 1 12 45 PM](https://user-images.githubusercontent.com/40493597/95243341-1d3f1000-07d6-11eb-8851-ec6334148db4.png)

I am getting an error now...

**Comment by parnic** [comment]
Does that error happen immediately or after some delay? You're still not hooking the correct event name (`getPumpStatus`), so an ECONNRESET would indicate that the connection is resetting due to, perhaps, a timeout.

**Comment by tjblevins** [comment]
Sorry... I am such an idiot. It was the event. I must have been drunk when I was typing that and even missed it again after you pointed it out earlier. Sorry... works like a champ now.
![image](https://user-images.githubusercontent.com/40493597/95250275-7bbcbc00-07df-11eb-8a97-ccd4140c4044.png)
